### PR TITLE
Completed prep-javascript-functions

### PR DESCRIPTION
**Pull request by BlakexLim**
prep functions console
prep functions
prep functions2
prep functions3

### CODE REVIEW

**Review by shawnkost — CHANGES_REQUESTED** [review]
Looks like you are missing quite a few of the functions we listed in the instructions. Please go back and reread the instructions and complete the functions you are missing

**Comment by BlakexLim** [comment]
Hello, just updated!

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Hey Blake, code looks good! One thing you want to update is the use of `const` to declare the variables in this exercise rather that `var` or `let`

I is best to avoid the use of `var` in new code, and `const` should be used anytime the variable value will not change, which would be all of the variables in this exercise. 


Let me know if you have any questions!

**Comment by BlakexLim** [comment]
Just changed all the var and let variables to const!

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
